//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bug_Management_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersProjects
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Users Users { get; set; }
    }
}
